// const quotes = [
//     "Mizu no Kokyū. Ichi no Kata: Minamo Giri",
//     "Mizu no Kokyū. Ni no Kata: Mizu Guruma",
//     "Mizu no Kokyū. San no Kata: Ryūryū Mai",
//     "Mizu no Kokyū. Shi no Kata: Uchishio",
//     "Mizu no Kokyū. Go no Kata: Kanten no Jiu",
//     "Mizu no Kokyū. Roku no Kata: Nejire Uzu",
//     "Mizu no Kokyū. Shichi no Kata: Shizuku Hamon Tsuki",
//     "Mizu no Kokyū. Hachi no Kata: Takitsubo",
//     "Mizu no Kokyū. Ku no Kata: Suiryū Shibuki",
//     "Mizu no Kokyū. Jū no Kata: Seisei Ruten",
//     "Mizu no Kokyū. Jū Ichi no Kata: Nagi",
//     "Honō no Kokyū. Ichi no Kata: Shiranui",
//     "Honō no Kokyū. Ni no Kata: Nobori En Ten",
//     "Honō no Kokyū. San no Kata: Kien Banjō",
//     "Honō no Kokyū. Shi no Kata: Sei En no Uneri",
//     "Honō no Kokyū. Go no Kata: Enko",
//     "Honō no Kokyū. Kyū no Kata: Rengoku",
//     "Kaminari no Kokyū. Ichi no Kata: Hekireki Issen",
//     "Kaminari no Kokyū. Ni no Kata: Inadama",
//     "Kaminari no Kokyū. San no Kata: Shūbun Seirai",
//     "Kaminari no Kokyū. Shi no Kata: Enrai",
//     "Kaminari no Kokyū. Go no Kata: Netsu Kairai",
//     "Kaminari no Kokyū. Roku no Kata: Dengō Raigō",
//     "Kaminari no Kokyū. Shichi no Kata: Honoikazuchi no Kami",
//     "Kedamono no Kokyū. Ichi no Kiba: Ugachi Nuki",
//     "Kedamono no Kokyū. Ni no Kiba: Kirisaki",
//     "Kedamono no Kokyū. San no Kiba: Kuizaki",
//     "Kedamono no Kokyū. Shi no Kiba: Kirikoma Zaki",
//     "Kedamono no Kokyū. Go no Kiba: Kuruizaki",
//     "Kedamono no Kokyū. Roku no Kiba: Ran Gui Gami",
//     "Kedamono no Kokyū. Shichi no Kata: Kūkan Shikikaku",
//     "Kedamono no Kokyū. Hachi no Kata: Bakuretsu Mōshin",
//     "Kedamono no Kokyū. Ku no Kata: Shinadori Geri",
//     "Kedamono no Kokyū. Jū no Kiba: Enten Senkai",
//     "Kedamono no Kokyū. Omoitsuki no Nageki",
//     "Hana no Kokyū. Ni no Kata: Mikage Ume",
//     "Hana no Kokyū. Shi no Kata: Beni Hanagoromo",
//     "Hana no Kokyū. Go no Kata: Ada no Shakuyaku",
//     "Hana no Kokyū. Roku no Kata: Uzumomo",
//     "Hana no Kokyū. Tsui no Kata: Higan Shugan",
//     "Mushi no Kokyū. Chō no Mai: Tawamure",
//     "Mushi no Kokyū. Hōga no Mai: Manabiki",
//     "Mushi no Kokyū. Seirei no Mai: Fukugan Rokkaku",
//     "Mushi no Kokyū. Gokō no Mai: Hyakusoku Jabara",
//     "Kaze no Kokyū. Ichi no Kata: Jinpū Sogi",
//     "Kaze no Kokyū. Ni no Kata: Sōsō・Shinato Kaze",
//     "Kaze no Kokyū. San no Kata: Seiran Fūjū",
//     "Kaze no Kokyū. Shi no Kata: Shōjō Sajinran",
//     "Kaze no Kokyū. Go no Kata: Kogarashi Oroshi",
//     "Kaze no Kokyū. Roku no Kata: Kokufū Enran",
//     "Kaze no Kokyū. Shichi no Kata: Keifū・Tengu Kaze",
//     "Kaze no Kokyū. Hachi no Kata: Sho Rekkaza Kiri",
//     "Kaze no Kokyū. Ku no Kata: Idaten Taifū",
//     "Kasumi no Kokyū. Ichi no Kata: Suiten Tōgasumi",
//     "Kasumi no Kokyū. Ni no Kata: Yaekasumi",
//     "Kasumi no Kokyū. San no Kata: Kasan no Shibuki",
//     "Kasumi no Kokyū. Shi no Kata: Iryūgiri",
//     "Kasumi no Kokyū. Go no Kata: Kaun no Umi",
//     "Kasumi no Kokyū. Roku no Kata: Tsuki no Kashō",
//     "Kasumi no Kokyū. Shichi no Kata: Oboro",
//     "Hebi no Kokyū. Ichi no Kata: Idagiri",
//     "Hebi no Kokyū. Ni no Kata: Kyōzu no Dokuga",
//     "Hebi no Kokyū. San no Kata: Toguro Jime",
//     "Hebi no Kokyū. Shi no Kata: Keija Sōsei",
//     "Hebi no Kokyū. Go no Kata: Enen Chōda",
//     "Koi no Kokyū. Ichi no Kata: Hatsukoi no Wananaki",
//     "Koi no Kokyū. Ni no Kata: Ōnō Meguru Koi",
//     "Koi no Kokyū. San no Kata: Koi Neko Shigure",
//     "Koi no Kokyū. Go no Kata: Yurameku Renjō・Midarezume",
//     "Koi no Kokyū. Roku no Kata: Neko Ashi Koi Kaze",
//     "Oto no Kokyū. Ichi no Kata: Todoroki",
//     "Oto no Kokyū. Shi no Kata: Kyōzan Muken",
//     "Oto no Kokyū. Go no Kata: Meigen Sōkyoku",
//     "Iwa no Kokyū. Ichi no Kata: Jamongan・Sōkyoku",
//     "Iwa no Kokyū. Ni no Kata: Tenmen Kudaki",
//     "Iwa no Kokyū. San no Kata: Ganku no Hadae",
//     "Iwa no Kokyū. Shi no Kata: Ryūongan・Sokusei",
//     "Iwa no Kokyū. Go no Kata: Garin Gyōbu",
//     "Hi no Kokyū. Enbu",
//     "Hi no Kokyū. Heki-ra no Ten",
//     "Hi no Kokyū. Retsujitsu Kōkyō",
//     "Hi no Kokyū. Gen'nichi Kō",
//     "Hi no Kokyū. Kasha",
//     "Hi no Kokyū. Shayō Tenshin",
//     "Hi no Kokyū. Hirin Kagerō",
//     "Hi no Kokyū. Yōkatotsu",
//     "Hi no Kokyū. Nichiun no Ryū Kaburimai",
//     "Hi no Kokyū. Faiyakku Hiyaku",
//     "Hi no Kokyū. Kiki Onkō",
//     "Hi no Kokyū. Jūsan no Kata",
//     "Tsuki no Kokyū. Ichi no Kata: Yamidzuki - Yoi no Miya",
//     "Tsuki no Kokyū. Ni no Kata: Shuka no Rōgetsu",
//     "Tsuki no Kokyū. San no Kata: Enkidzuki - Tsugari",
//     "Tsuki no Kokyū. Go no Kata: Geppaku Saika",
//     "Tsuki no Kokyū. Roku no Kata: Tokoyo Kogetsu - Muken",
//     "Tsuki no Kokyū. Shichi no Kata: Yakkyō - Dzukibae",
//     "Tsuki no Kokyū. Hachi no Kata: Getsuryū Rinbi",
//     "Tsuki no Kokyū. Ku no Kata: Kudaridzuki - Renmen",
//     "Tsuki no Kokyū. Jū no Kata: Senmenzan - Ragetsu",
//     "Tsuki no Kokyū. Jūshi no Kata: Kyōhen - Tenman Sengetsu",
//     "Tsuki no Kokyū. Jūroku no Kata: Gekkō - Katawaredzuki",
// ];

import loadingGif from "../assets/zenitsu.gif";

export function Loading() {
    // const i = Math.floor(Math.random() * quotes.length);
    // const q = quotes[i];

    return (
        <div>
            {/* <p className="italic text-gray-400">{q}</p> */}
            <img src={loadingGif} alt="loading" className="w-full opacity-30" />
        </div>
    );
}
