/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagePageRouteImport } from './routes/page/$page'
import { Route as CategoryCategoryRouteImport } from './routes/category/$category'
import { Route as AnimeSlugRouteImport } from './routes/anime/$slug'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagePageRoute = PagePageRouteImport.update({
  id: '/page/$page',
  path: '/page/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeSlugRoute = AnimeSlugRouteImport.update({
  id: '/anime/$slug',
  path: '/anime/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/page/$page': typeof PagePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/page/$page': typeof PagePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/page/$page': typeof PagePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/anime/$slug'
    | '/category/$category'
    | '/page/$page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/anime/$slug' | '/category/$category' | '/page/$page'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/anime/$slug'
    | '/category/$category'
    | '/page/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnimeSlugRoute: typeof AnimeSlugRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  PagePageRoute: typeof PagePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$page': {
      id: '/page/$page'
      path: '/page/$page'
      fullPath: '/page/$page'
      preLoaderRoute: typeof PagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$slug': {
      id: '/anime/$slug'
      path: '/anime/$slug'
      fullPath: '/anime/$slug'
      preLoaderRoute: typeof AnimeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnimeSlugRoute: AnimeSlugRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  PagePageRoute: PagePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
